/****** Script do comando SelectTopNRows de SSMS  ******/

SELECT  CAMPANHA
		,DATA
		,COUNT(AGENTNAME) AS ENTRADAS
FROM(
SELECT CASE WHEN CAMPAIGNID IN (10,47,48) THEN 'Claro Aquisicao'
			WHEN CAMPAIGNID IN (68,70,71,72) THEN 'Claro Migracao' END AS CAMPANHA
		,AGENTNAME
		,CONVERT(VARCHAR,MIN(CALLSTART),103) AS DATA
  FROM [DBM_BASE].[dbo].[TB_HISTORICO_DBM_CLARO_OLOS] WITH(NOLOCK)
  WHERE CALLSTART BETWEEN '2020-02-01' AND '2020-05-30' AND CAMPAIGNID IN (10,47,48,68,70,71,72) AND AGENTNAME IS NOT NULL
  GROUP BY CASE WHEN CAMPAIGNID IN (10,47,48) THEN 'Claro Aquisicao'
			WHEN CAMPAIGNID IN (68,70,71,72) THEN 'Claro Migracao' END
			,AGENTNAME) AS A
GROUP BY CAMPANHA, DATA
