SELECT 

DATEPART(hour, DATA_HORA_FIM_ATENDIMENTO) AS HORA
,CONVERT(VARCHAR, DATA_HORA_FIM_ATENDIMENTO, 103) AS DIA
,[CAMPANHA]
,COUNT(DISTINCT NOME_AGENTE) AS AGENTES_LOGADOS

FROM [SVSPODB01].[DBM_BASE].[dbo].[TB_HISTORICO_HMB_CLARO_MIGRACAO]

WHERE DATA_HORA_FIM_ATENDIMENTO between '2020-08-01 00:00:00' and '2020-08-06 23:00'

GROUP BY CAMPANHA