USE MIS

SELECT CONVERT(VARCHAR, CALLSTART, 103), STATUS_DESCRIPTION, COUNT(1) AS TABULADAS
		FROM PC_TENTATIVAS_AQUISICAO
		WHERE AGENTNAME IS NOT NULL AND MONTH(CALLSTART) = 8
	GROUP BY CONVERT(VARCHAR, CALLSTART, 103), STATUS_DESCRIPTION
