--Tabulacao
-----------------------------------------------------------------------------------------------------------------
SELECT CONVERT(VARCHAR, CALLSTART, 103) AS DATA, STATUS_DESCRIPTION, COUNT(1) AS TOTAL
FROM PC_TENTATIVAS_AQUISICAO
WHERE AGENTNAME IS NOT NULL AND MONTH(CALLSTART) = 6
GROUP BY CONVERT(VARCHAR, CALLSTART, 103), STATUS_DESCRIPTION


-- BASE DIARIO
------------------------------------------------------------------------------------------------------------------

SELECT CONVERT(VARCHAR, CALLSTART, 103) AS DATA, COUNT(DISTINCT PHONENUMBER) AS CLIENTES
            ,SUM(CASE WHEN AGENTNAME IS NOT NULL THEN 1 ELSE 0 END) AS ATENDIDA ,COUNT(1) AS TENTATIVAS
            ,SUM(CASE WHEN DISPOSITIONID IN (109,110,112,115,117,132,155,156) THEN 1 ELSE 0 END) AS EFETIVO
      FROM PC_TENTATIVAS_AQUISICAO
      WHERE MONTH(CALLSTART) = 6
      GROUP BY CONVERT(VARCHAR, CALLSTART, 103)

------------------------------------------------------------------------------------------------------------------

-- CRIAR TABELAS TEMPORTARIAS / EXECULTAR UMA DE CADA VEZ
-------------------------------------------------------------------------------------------------------------------
SELECT PHONENUMBER
            ,COUNT(1) AS SPIN
            INTO #DISCAGENS
            FROM PC_TENTATIVAS_AQUISICAO
            WHERE CAMPAIGNID NOT IN (127,167,171)
            GROUP BY PHONENUMBER
            
           
            
SELECT DISTINCT PHONENUMBER INTO #DISCADO FROM PC_TENTATIVAS_AQUISICAO
WHERE CAMPAIGNID NOT IN (127,167,171)

SELECT DISTINCT PHONENUMBER INTO #ATENDIDA FROM PC_TENTATIVAS_AQUISICAO
WHERE CAMPAIGNID NOT IN (127,167,171) AND AGENTNAME IS NOT NULL

SELECT DISTINCT PHONENUMBER INTO #IMPRODUTIVA FROM PC_TENTATIVAS_AQUISICAO
WHERE DISPOSITIONID IN (102,103,104,105,106,107,108,126,127) AND CAMPAIGNID NOT IN (127,167,171)

SELECT DISTINCT PHONENUMBER INTO #AGENDAMENTO FROM PC_TENTATIVAS_AQUISICAO
WHERE DISPOSITIONID IN (100,101) AND CAMPAIGNID NOT IN (127,167,171)

SELECT DISTINCT PHONENUMBER INTO #RECUSA FROM PC_TENTATIVAS_AQUISICAO
WHERE DISPOSITIONID IN (109,110,112,115,117,132,155,156) AND CAMPAIGNID NOT IN (127,167,171)

SELECT DISTINCT PHONENUMBER INTO #INAPTA FROM PC_TENTATIVAS_AQUISICAO
WHERE DISPOSITIONID IN (111,113,114) AND CAMPAIGNID NOT IN (127,167,171)

SELECT DISTINCT TELEFONE_CONTATO INTO #VENDAS FROM [SVSPODB01].[DBM_BASE].[dbo].[TB_HISTORICO_HMB_CLARO_MIGRACAO]
  WHERE DATA_HORA_INICIO_ATENDIMENTO BETWEEN '2020-01-04' AND '2020-30-07' AND [TIPO DE STATUS DA OFERTA] = 'ACEITE'
  AND CAMPANHA LIKE 'CLARO AQUISICAO%' AND MAILING NOT LIKE '%voice%'



-------------------------------------------------------------------------------------------------------------------------

--Base Consolidado
-------------------------------------------------------------------------------------------------------------------------
SELECT 
            DT_INICIO_VIGENCIA
            ,A.OPERADORA
            ,LEFT(A.TELEFONE,2) AS DDD
            ,A.COD_REGIONAL
            ,'AQUISICAO' AS ACAO
            ,COUNT(DISTINCT A.TELEFONE) AS VOLUME
            ,SUM(B.SPIN) AS DISCAGENS
            ,COUNT(DISTINCT C.PHONENUMBER) AS DISCADO
            ,COUNT(DISTINCT D.PHONENUMBER) AS ATENDIDA
            ,COUNT(DISTINCT E.PHONENUMBER) AS IMPRODUTIVA
            ,COUNT(DISTINCT F.PHONENUMBER) AS AGENDAMENTO
            ,COUNT(DISTINCT G.PHONENUMBER) AS RECUSA
            ,COUNT(DISTINCT H.PHONENUMBER) AS INAPTA
            ,COUNT(DISTINCT I.TELEFONE_CONTATO) AS INAPTA
      FROM MAILING_AQUISICAO AS A
            LEFT JOIN
            #DISCAGENS AS B
            ON A.TELEFONE COLLATE SQL_Latin1_General_CP1_CI_AS = B.PHONENUMBER
            LEFT JOIN
            #DISCADO AS C
            ON A.TELEFONE COLLATE SQL_Latin1_General_CP1_CI_AS = C.PHONENUMBER
            LEFT JOIN
            #ATENDIDA AS D
            ON A.TELEFONE COLLATE SQL_Latin1_General_CP1_CI_AS = D.PHONENUMBER
            LEFT JOIN
            #IMPRODUTIVA AS E
            ON A.TELEFONE COLLATE SQL_Latin1_General_CP1_CI_AS = E.PHONENUMBER
            LEFT JOIN
            #AGENDAMENTO AS F
            ON A.TELEFONE COLLATE SQL_Latin1_General_CP1_CI_AS = F.PHONENUMBER
            LEFT JOIN
            #RECUSA AS G
            ON A.TELEFONE COLLATE SQL_Latin1_General_CP1_CI_AS = G.PHONENUMBER
            LEFT JOIN
            #INAPTA AS H
            ON A.TELEFONE COLLATE SQL_Latin1_General_CP1_CI_AS = H.PHONENUMBER
            LEFT JOIN
            #VENDAS AS I
            ON A.TELEFONE COLLATE SQL_Latin1_General_CP1_CI_AS = I.TELEFONE_CONTATO
GROUP BY DT_INICIO_VIGENCIA
            ,A.OPERADORA
            ,LEFT(A.TELEFONE,2)
            ,A.COD_REGIONAL
--------------------------------------------------------------------------------------------------------------------------       

--------------------------------------------------------------------------------------------------------------------------
DROP TABLE #DISCAGENS
DROP TABLE #DISCADO
DROP TABLE #ATENDIDA
DROP TABLE #IMPRODUTIVA
DROP TABLE #AGENDAMENTO
DROP TABLE #RECUSA
DROP TABLE #INAPTA
DROP TABLE #VENDAS
---------------------------------------------------------------------------------------------------------------


-- TABELAS VIRTUAIS AGV| EXECULTAR UMA POR UMA
------------------------------------------------------------------------------------------------------------
SELECT PHONENUMBER, COUNT(1) AS TENTATIVAS INTO #TENTATIVAS FROM PC_TENTATIVAS_2
WHERE CAMPAIGNID IN (126,166,170)
GROUP BY PHONENUMBER

SELECT DISTINCT PHONENUMBER INTO #DISCADO FROM PC_TENTATIVAS_2

SELECT DISTINCT CUSTOMERID, PHONENUMBER INTO #ALO FROM PC_TENTATIVAS_2
WHERE STATUS_DESCRIPTION LIKE 'Trans%' 

SELECT DISTINCT CUSTOMERID INTO #TRANSFERIDO FROM PC_TENTATIVAS_AQUISICAO
WHERE CAMPAIGNID IN (127, 167,171) AND AGENTNAME IS NOT NULL

SELECT DISTINCT CUSTOMERID INTO #AGENDAMENTO FROM PC_TENTATIVAS_AQUISICAO
WHERE CAMPAIGNID IN (127, 167,171) AND DISPOSITIONID IN (100,101)

SELECT DISTINCT [TELEFONE]
      ,[OPERADORA]
      ,LEFT(TELEFONE,2) AS DDD
      ,[COD_REGIONAL]
      ,'18/mai' AS SAFRA
      ,CASE WHEN B.["cep"] IS NOT NULL THEN 'POSSIBILIDADE EXPRESS' ELSE 'CORREIO' END AS ENVIO 
 INTO #MAILING FROM dbo.Mailing_Aquisicao AS A
WHERE 
LEFT JOIN
telefone_vs_cep AS B
ON A.TELEFONE = B.["telefone"]


SELECT DISTINCT TELEFONE_CONTATO INTO #VENDAS FROM [SVSPODB01].[DBM_BASE].[dbo].[TB_HISTORICO_HMB_CLARO_MIGRACAO]
  WHERE DATA_HORA_INICIO_ATENDIMENTO BETWEEN '2020-07-01' AND '2020-07-30' AND [TIPO DE STATUS DA OFERTA] = 'ACEITE'
  AND CAMPANHA LIKE 'CLARO AQUISICAO%'
---------------------------------------------------------------------------------------------------------------------------


--Base Resumo
--------------------------------------------------------------------------------------------------------------------------
SELECT
            'B'
            ,Safra
            ,A.OPERADORA
            ,A.COD_REGIONAL
            ,A.DDD
            ,ENVIO
            ,COUNT(DISTINCT A.TELEFONE) AS TOTAL
            ,COUNT(DISTINCT CASE WHEN B.PHONENUMBER IS NULL THEN A.TELEFONE END) AS VIRGEM
            ,SUM(B.TENTATIVAS) AS TENTATIVAS
            ,COUNT(DISTINCT C.PHONENUMBER) AS DISCADO
            ,COUNT(DISTINCT D.PHONENUMBER) AS ATENDIDA
            ,COUNT(DISTINCT E.CUSTOMERID) AS TRANSFERIDO
            ,COUNT(DISTINCT F.CUSTOMERID) AS AGENDAMENTO
            ,COUNT(DISTINCT G.TELEFONE_CONTATO) AS VENDAS
      FROM #MAILING AS A
      LEFT JOIN
      #TENTATIVAS AS B
      ON A.TELEFONE COLLATE SQL_Latin1_General_CP1_CI_AS = B.PHONENUMBER
      LEFT JOIN
      #DISCADO AS C
      ON B.PHONENUMBER = C.PHONENUMBER
      LEFT JOIN
      #ALO AS D
      ON C.PHONENUMBER = D.PHONENUMBER
      LEFT JOIN
      #TRANSFERIDO AS E
      ON D.CUSTOMERID = E.CUSTOMERID
      LEFT JOIN
      #AGENDAMENTO AS F
      ON E.CUSTOMERID = F.CUSTOMERID
      LEFT JOIN
      #VENDAS AS G
      ON A.TELEFONE = G.TELEFONE_CONTATO
GROUP BY Safra
                  ,A.OPERADORA
            ,A.COD_REGIONAL
            ,A.DDD
            ,ENVIO

