SELECT 
			CONVERT(VARCHAR, CALLSTART, 103) AS DATA
            ,COUNT(1) AS DISCAGENS
            ,SUM(CASE WHEN AGENTNAME IS NOT NULL THEN 1 ELSE 0 END) AS ALO
            ,SUM(CASE WHEN DISPOSITIONID IN (110,112,115,117,132) THEN 1 ELSE 0 END) AS EFETIVO
      FROM PC_TENTATIVAS_AQUISICAO
      WHERE CAMPAIGNID = 171
      GROUP BY CONVERT(VARCHAR, CALLSTART, 103)
