USE MIS 

SELECT PHONENUMBER, COUNT(1) AS TENTATIVAS INTO #TENTATIVAS FROM PC_TENTATIVAS_2
WHERE CAMPAIGNID IN (126,176) AND CALLSTART BETWEEN '2020-01-06' AND '2020-06-30'
GROUP BY PHONENUMBER


SELECT DISTINCT PHONENUMBER INTO #DISCADO FROM PC_TENTATIVAS_2
WHERE CALLSTART BETWEEN '2020-01-01' AND '2020-06-30'

SELECT DISTINCT CUSTOMERID, PHONENUMBER INTO #ALO FROM PC_TENTATIVAS_2
WHERE STATUS_DESCRIPTION LIKE 'Transf%'
AND CALLSTART BETWEEN '2020-01-01' AND '2020-06-30'

SELECT DISTINCT CUSTOMERID INTO #TRANSFERIDO FROM PC_TENTATIVAS_AQUISICAO
WHERE CAMPAIGNID IN (127)
AND CALLSTART BETWEEN '2020-01-01' AND '2020-06-30'

SELECT DISTINCT CUSTOMERID INTO #AGENDAMENTO FROM PC_TENTATIVAS_AQUISICAO
WHERE CAMPAIGNID IN (127, 167) AND DISPOSITIONID IN (100,101)
AND CALLSTART BETWEEN '2020-01-01' AND '2020-06-30'

SELECT DISTINCT TELEFONE_CONTATO INTO #VENDAS FROM [SVSPODB01].[DBM_BASE].[dbo].[TB_HISTORICO_HMB_CLARO_MIGRACAO]
  WHERE DATA_HORA_INICIO_ATENDIMENTO BETWEEN '2020-01-01' AND '2020-06-30' AND [TIPO DE STATUS DA OFERTA] = 'ACEITE'
  AND CAMPANHA LIKE 'CLARO AQUISICAO%'

SELECT DISTINCT * INTO #MAILING FROM MAILNG_SALESBOT
WHERE SAFRA = '01/06/2020'


SELECT
            'Lado A'
            ,A.OPERADORA
            ,A.COD_REGIONAL
            ,A.DDD
            ,COUNT(DISTINCT A.TELEFONE) AS TOTAL
            ,COUNT(DISTINCT CASE WHEN B.PHONENUMBER IS NULL THEN A.TELEFONE END) AS VIRGEM
            ,SUM(B.TENTATIVAS) AS TENTATIVAS
            ,COUNT(DISTINCT C.PHONENUMBER) AS DISCADO
            ,COUNT(DISTINCT D.PHONENUMBER) AS ATENDIDA
            ,COUNT(DISTINCT E.CUSTOMERID) AS TRANSFERIDO
            ,COUNT(DISTINCT F.CUSTOMERID) AS AGENDAMENTO
            ,COUNT(DISTINCT G.TELEFONE_CONTATO) AS VENDAS
      FROM #MAILING AS A
      LEFT JOIN
      #TENTATIVAS AS B
      ON A.TELEFONE COLLATE SQL_Latin1_General_CP1_CI_AS = B.PHONENUMBER
      LEFT JOIN
      #DISCADO AS C
      ON B.PHONENUMBER = C.PHONENUMBER
      LEFT JOIN
      #ALO AS D
      ON C.PHONENUMBER = D.PHONENUMBER
      LEFT JOIN
      #TRANSFERIDO AS E
      ON D.CUSTOMERID = E.CUSTOMERID
      LEFT JOIN
      #AGENDAMENTO AS F
      ON E.CUSTOMERID = F.CUSTOMERID
      LEFT JOIN
      #VENDAS AS G
      ON A.TELEFONE = G.TELEFONE_CONTATO
GROUP BY A.OPERADORA
            ,A.COD_REGIONAL
            ,A.DDD
            
            
        DROP TABLE #MAILING
        DROP TABLE #TENTATIVAS
        DROP TABLE #DISCADO
        DROP TABLE #ALO
        DROP TABLE #TRANSFERIDO
        
        DROP TABLE #AGENDAMENTO
        DROP TABLE #VENDAS
